Lets Fame - Feb code changes and additional implements
arulselvamatv/Letsfame-Java pull request #15
Opened 2023-03-06 06:35 UTC by Ansariac

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/Req/LetsFameOrderReq.java
> +package com.letsfame.Req;
package name is not updated, change it to 

com.letsfame.request;

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/Req/LetsFameOrderReq.java
> +public class LetsFameOrderReq {
Rename the class from LetsFameOrderReq to either OrderCreateRequest or OrderUpdateRequest based on the operation

**!Important!** remove all LetsFame from all requests and model class

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/advice/CustomExceptionHandler.java
> +		log.info("Exception:"+ExceptionUtils.getStackTrace(ex));
merge both loggers into a single one, there is no need of having two loggers

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/bean/LetsFameOrder.java
> +public class LetsFameOrder implements Serializable {
rename class name to Order

**Important** follow the same for remaining classes

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/config/AppConfig.java
>  @EnableWebMvc
why you have used EnableWebMvc annotation here,

can we have a common config class for all the beans?

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/config/SwaggerConfig.java
>  @EnableAutoConfiguration
why do we have EnableAutoConfiguration annotation here?

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/config/SwaggerConfig.java
> +public class SwaggerConfig extends WebMvcConfigurationSupport {
why WebMvcConfigurationSupport is extended and what s the use of it

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/config/SwaggerConfig.java
have a common config for all kind of bean initialization

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/config/SwaggerConfig.java
>  @EnableSwagger2
Springboot supports Swagger, why have you used springfox external library for the swagger?

please use Springboot library

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/controller/OrderController.java
> +public class OrderController {
What is the use of OrderContoller and Payment Controller and Subscription controller? why do we need all these three?

post this info in the group

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/bean/WebhookPaymentDetails.java
> +@Document(collection = "Webhook")
there is no need of creating Webhook collection, we not all need to store them in our database inself

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/dto/SubscriptionsDto.java
>  public class SubscriptionsDto implements Serializable {
what is the use of dto package and repository package? cant we have it single package

explain this in group?

2023-03-08 16:38 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +	private WebhooksRepository webHooksRepository;
there is no need of storing them in the Database itself please remove this. if you ahve more questions please reach me

2023-03-08 16:55 UTC, Silaluthirapathi commented on src/main/java/com/letsfame/advice/CustomExceptionHandler.java
> +		log.info("Exception:"+ExceptionUtils.getStackTrace(ex));
Errors are logged as ERROR not INFO and Check about parametrized logger and implement the same.

2023-03-08 17:44 UTC, Silaluthirapathi commented on src/main/java/com/letsfame/Req/LetsFamePlanItemReq.java
> +	@JsonProperty("description")
Here @jsonproperty necessity is not required here. why do you use the annotation? Please understand the purpose of jsonproperty annotation and use it.

@Pikazza Please have a look on this?

2023-03-08 17:48 UTC, Silaluthirapathi commented on src/main/java/com/letsfame/Req/LetsFameOrderReq.java
> +	private String currency;
@Pikazza Please provide your comment on this?

2023-03-08 17:53 UTC, Silaluthirapathi requested changes
@sathishkumar144625 , @Pikazza added few comments. Please address those comments.

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +	private WebhooksRepository webHooksRepository;
Remove WebhooksRepository Autowiring itself

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
>  		System.out.println("webhook ::" + notification);
please change it to logger

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +		WebhookPaymentDetails savedData1 = new WebhookPaymentDetails();
Webhook event is common for both Payment and subscriptions. so please change the name WebhookPaymentDetails to a generic name like WebhookEvent

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +		System.out.println("invoice_details::" + invoice);
change it to logger

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +		LetsFamePayment payments = paymentService
there is no need of having plural name for a single payment

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +			System.out.println("Payments status updated Sucessfully ::" + savedData1);
1. please change it to the logger
2. please remove saving  mehanism

2023-03-14 17:55 UTC, Pikazza commented on src/main/java/com/letsfame/serviceImpl/WebhookServiceImpl.java
> +		WebhookPaymentStatusByMember paymentstatus = new WebhookPaymentStatusByMember();
change the class name WebhookPaymentStatusByMember

2023-03-21 04:04 UTC, Pikazza approved these changes

2023-03-22 03:30 UTC, Pikazza approved these changes

2023-03-22 03:30 UTC, Pikazza approved these changes

2023-03-22 03:31 UTC, arulselvamatv approved these changes
approved

2023-03-22 03:31 UTC, Pikazza approved these changes
code looking fine

2023-03-22 03:33 UTC, arulselvamatv approved these changes

2023-03-22 03:34 UTC, arulselvamatv approved these changes
approve

2023-03-22 06:32 UTC, Silaluthirapathi approved these changes
LGTM

2023-03-22 06:43 UTC, merged